### ISSUE TITLE
Ping to /api/ rather than /

### ISSUE THREAD

**Issue by PullJosh** [dkter/weecent#4]
https://github.com/TheInitializer/weecent/blob/d2b178b634f0d4bf01221f795628a8e2195da989/weecent.py#L40-L41

When checking to see if a server is online and avilable, shouldn't you be checking for a 418 at `/api/`?

**Edit**
The reasoning for this doesn't appear to be documented at all in the Decent wiki. Here's the related piece of code to explain why:
https://github.com/towerofnix/decent/blob/master/api.js#L407-L422

**Comment by TheInitializer** [comment]
huh, ok. will do!
